version: '3.7'

services:

  db:
    image: postgres:15-alpine
    volumes: 
      - ./db_data/db:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_DB=web
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - my-network

  backend:
    build: ./things
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - SQL_DATABASE=postgresql
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DATABASE=postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge