# Generated by Django 4.1.3 on 2022-11-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things_backend', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='<property object at 0x7fc5f92fcef0>/<property object at 0x7fc5f9026b10>/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='things_backend.photo', verbose_name='Фото'),
        ),
    ]
