# Generated by Django 4.1.3 on 2022-11-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_backend', '0004_remove_post_image_id_alter_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='<property object at 0x7f5c986569d0>/<property object at 0x7f5c98656430>/'),
        ),
    ]
