# Generated by Django 4.1.3 on 2022-11-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_backend', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='<property object at 0x7f65be03a8e0>/<property object at 0x7f65be03a2f0>/'),
        ),
    ]
