# Generated by Django 4.1.3 on 2022-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_backend', '0009_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
